### ISSUE TITLE
action step got stuck while the previous run was finished long time back

### ISSUE THREAD

**Issue by chenrui333** [softprops/turnstyle#10]
Action step log

```
✋Awaiting run https://github.com/meetup/meetup/actions/runs/163182442...
##[error]The action has timed out.
```

However that action run was finished 10 hours before.

**Comment by chenrui333** [comment]
More context would be, I have temporarily disabled the action step, have the workflow run successfully, and then the revert commit failed with the exact action run check.

```
✋Awaiting run https://github.com/meetup/meetup/actions/runs/163182442...
##[error]The operation was canceled.
```

**Comment by softprops** [comment]
The previous run pool behavior recently changed to avoid race condition. 

Instead action now selects for [all active runs with a run id less than that of its own](https://github.com/softprops/turnstyle/blob/64882c20d87df5b6d5c722af0e8c2206404a1f44/src/wait.ts#L35-L48) on each polling. The workflow run it's awaiting might not always be immediately previous run. It's **any active run that precedes it** which can be multiple runs if a queue of runs is large enough. 

To override this behavior you may wish to set number [timeout-minutes](https://github.com/softprops/turnstyle#timing-out).

**Comment by Coobaha** [comment]
It seems that new behaviour is not working correctly, We have exactly the same issue as @chenrui333 mentioned action run was finished already long time ago.

**Comment by softprops** [comment]
Can either of you provide some helpful information to move this forward?

 The assumption I'm running with here is that the runs being queried are all [in_progress](https://github.com/softprops/turnstyle/blob/64882c20d87df5b6d5c722af0e8c2206404a1f44/src/github.ts#L71). Each time an enqueued run decides to wait, it [prints the link for the fun being waited on](https://github.com/softprops/turnstyle/blob/64882c20d87df5b6d5c722af0e8c2206404a1f44/src/wait.ts#L49) .

If possible could either of you show be the logs with timestamps (you can use the action logs ui to annotate logs with these) when this runs link was printed and then grab the link for the action that was presumed complete and share it's completion time.

I'd like to collect some data to see if it's completion time was indeed before the timestamp the actions api indicated it was `in_progress` for further analysis.

**Comment by softprops** [comment]
Another factor of interest I had not updated the release to include https://github.com/softprops/turnstyle/pull/8 yet. This may be of some interest of the trigger in use is a `pull_request`.

 In most of my own use cases for this action the context is more likely a `push` event to a master (or default) branch for the common case of deploy-on-master-pushes workflow

**Comment by chenrui333** [comment]
I have some new idea, maybe deleting the workflow run and rerun might work.

**Comment by chenrui333** [comment]
I pulled down the action runs, did not observe anything weird, and then I uncomment my action step. It works for us now.

**Comment by chenrui333** [comment]
> It seems that new behaviour is not working correctly, We have exactly the same issue as @chenrui333 mentioned action run was finished already long time ago.

@Coobaha, do you want to try out commenting out the step, give it a day or two, and then uncomment to see what's going to happen?

As my issue got resolved, closing this issue now.

**Comment by softprops** [comment]
Thanks folks. If someone should find this in the future the bug reported I'd like to see is one that shows a screenshot of the link to the run being awaited on with a timestamp showing when it was being awaited and a screen short of the linked run showing that it was actually completed before that time
