### ISSUE TITLE
Workflows do not get serialized if GITHUB_TOKEN is at workflow level

### ISSUE THREAD

**Issue by carmenberndt** [softprops/turnstyle#13]
If the GITHUB_TOKEN is at the workflow level, the action does not get executed correctly, i.e. workflows do not get serialized.  Looks like a bug in this GH action.

If the `GITHUB_TOKEN` is used in multiple places, it only makes sense adding it to a higher level than only step level.

**Comment by softprops** [comment]
👋 Can you fill me in with with an example of your workflow config and possible a few runs?

The examples in this repo assumes  the GITHUB_TOKEN provisions for you which provides a setting of permissions. You can however generate a personal access token. If you manually generating a personal access token can you share what permissions you are granting it?

**Comment by carmenberndt** [comment]
Does your GH action need to be specified once on every job in a workflow or only once per workflow? 

I'm using GITHUB_TOKEN, so the permissions are not the problem. 
An example of a workflow file is here: https://github.com/prisma/language-tools/blob/master/.github/workflows/publish-insider-check-CLI.yml

And here are a few runs: 
- for example this run got executed fine: https://github.com/prisma/language-tools/actions/runs/202824251
- but this run should have waited till the job was done: https://github.com/prisma/language-tools/actions/runs/202841880 but it failed, since the first one was still running even though this script uses this GH action

**Comment by softprops** [comment]
We've only documented injecting `GITHUB_TOKEN` once per step that uses it to follow principle of least privilege in what has access to it. 

The action it self just uses what ever is stored in [`env.GITHUB_TOKEN`](https://github.com/softprops/turnstyle/blob/a860a95b01b5b2b26c76351cdbf37df10eab8da5/src/input.ts#L14) so in theory if you're making available in the env by declaring it above not much would change but moving into a local step scope.

I'll take a look at your run logs and see what looks off.

**Comment by softprops** [comment]
closing this for now as this action leaves providing `GITHUB_TOKEN`  up to users. It does not special case where it is provided but only assumes that it its present
