### ISSUE TITLE
How does it work with multiple workflows?

### ISSUE THREAD

**Issue by arvidviderberg** [softprops/turnstyle#14]
Hello, and thanks for creating this! It looks great.

How does the action handle multiple workflows? Lets say I have workflow A and B and I normally run them concurrently. If I add turnstyle to both Workflows then will:
* Workflow A only wait for other workflows of type A?
* Workflow A wait for workflows of both types A and B?

Thanks!

**Comment by softprops** [comment]
This action serializes on a target workflow and not across workflows. 

The target usecase is continuous deployment. GitHub will trigger worflow and run them in parallel. This action provides a way to serialize those runs at a given step, typically the deployment step in practice. This allows you to avoid problematic case of multiple merged interrupting an in progress deployment

So in a sense 

> Workflow A only wait for other workflows of type A?

In general if you have cross workflow dependencies, it's a potential signal that you may want to restructure into a single workflow. Can you elaborate on your usecases in a bit more detail?

**Comment by arvidviderberg** [comment]
Thanks for clarifying! I'm using two workflows but they're independent of each other, so this works just fine. Added turnstyle to my workflow a few days ago, works like a charm. Thanks again for making this!

**Comment by softprops** [comment]
Cool. Don't hesitate to reach out if you have more questions
