### ISSUE TITLE
Not sure why jobs are running concurrently

### ISSUE THREAD

**Issue by ronlut** [softprops/turnstyle#15]
Thanks for the great action.
I have a pretty simple scenario where I want to limit a job to never run concurrently (deploy to github pages).
Can't get it to work for some reason, probably missing something.

My workflow is [here](https://github.com/ronlut/jsonperf/blob/master/.github/workflows/deploy.yaml) and the runs are [#1](https://github.com/ronlut/jsonperf/runs/1091585632) [#2](https://github.com/ronlut/jsonperf/runs/1091588164) (had to cancel the 2nd as it already started without waiting for the first one).
Relevant job to block is `gh-pages` ("Deploying to Github Pages")

Thanks

**Comment by tymokvo** [comment]
Hi I also have the same issue. It is happening on a private repo so I can't share any workflow logs but would be happy to provide debug info if there is something specific that I can look for.

Thanks for making this though! GH workflows really should have this built-in.

**Comment by adam-skalicky** [comment]
This may be unrelated, but I had a similar issue.

I ended up removing the following  from my yaml file that was under the linux section to resolve it :

```
    strategy:
      matrix:
        node_version: [12.x]
```

**Comment by schof** [comment]
@ronlut Your workflow doesn't have the action configured (`softprops/turnstyle@v1`). See the README on that.

**Comment by onedr0p** [comment]
@schof take a look at his git history, he had it there but I guess it wasn't working for him so he removed it.

**Comment by vigneshmsft** [comment]
@ronlut @tymokvo , the problem could be related to what we are facing too, I have raised a PR for this #31 
In my testing I found out the action wasn't pulling `queued` runs and this was allowing runs to progress without waiting.

**Comment by chenrui333** [comment]
Close as fixed. Thanks!

**Comment by chenrui333** [comment]
Try out 2.1.0 release.

**Comment by onedr0p** [comment]
What a great comeback!
