### ISSUE TITLE
Abort-after-seconds

### ISSUE THREAD

**Issue by siemensikkema** [softprops/turnstyle#18]
In addition to the `continue-after-seconds` I could see a good use-case for an `abort-after-seconds` option such that the waiting step doesn't exceed some limit. You could set a `timeout-minutes` on the whole job but then you have to take into account how long you expect a normal run to take. Am I missing something? Can this be done another way already?

**Comment by GMNGeoffrey** [comment]
This seems pretty straightforward to implement. @softprops would you accept a PR for this feature?

**Comment by softprops** [comment]
That sounds reasonable. Just to confirm the difference would be failing the job rather than pressing on? That makes sense to me.

**Comment by GMNGeoffrey** [comment]
Yup, exactly. I figure it can throw an error in the waiter which will then propagate up to main

**Comment by jbasila-orca** [comment]
Another use case is when you would like to send some sort of notification (a custom notification using `if: failure()` when the job didn't run.

Using `timeout-minutes` will cancel the whole job and thus no notification will be sent, but if the `timeout-minutes` is set properly, and only the `abort-after-seconds` will trigger the failure, then the notification step will be executed and the user will be notified that the job was canceled.
