### ISSUE TITLE
New release with latest changes

### ISSUE THREAD

**Issue by belitre** [softprops/turnstyle#21]
Hi @softprops 

Just wondering if you are planning to update the `v1` tag, or release a new one with the change with `abort-after-seconds`.

I really don't like to use `master` for the action version, since a breaking change could break my workflows :)

Thank you very much!

**Comment by belitre** [comment]
Oh, and thank you very much for this action! :)

**Comment by softprops** [comment]
I'll try to get that by the end of the week.

**Comment by softprops** [comment]
updated the v1 one tag with all of the last changes

**Comment by belitre** [comment]
@softprops Thank you very much!
