### ISSUE TITLE
[Security] Update @actions/core to 1.2.6

### ISSUE THREAD

**Issue by past-due** [softprops/turnstyle#25]
See blog post: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

> Action authors who are using the toolkit should update the @actions/core package to v1.2.6 or greater to get the updated addPath and exportVariable functions.

> Action and workflow authors who are setting environment variables via STDOUT should update any usage of the set-env and add-path workflow commands to use the new environment files.

> If you need to log untrusted information such as issue titles, bodies, or commit messages to STDOUT we recommend that you disable command processing prior to doing that.

**Comment by chenrui333** [comment]
Close as fixed. Thanks!
