### ISSUE TITLE
GitHub doesn't allow `GITHUB_TOKEN` as a name

### ISSUE THREAD

**Issue by pierskarsenbarg** [softprops/turnstyle#37]
Looks like GitHub isn't allowing secrets that start with `GITHUB_` anymore:

![image](https://user-images.githubusercontent.com/109047/129003742-cbedf6e1-d228-46a1-a63b-5e6177498aa5.png)

**Comment by softprops** [comment]
Does a different name for the secret work?

**Comment by pierskarsenbarg** [comment]
It does (that's what I did) but the examples no longer work for people who will copy and paste them. 

And what's the point of having examples that you can't copy and pasted?

**Comment by sekhavati** [comment]
If you're referring to the `GITHUB_TOKEN` secret mentioned in the docs it's [automatically created](https://docs.github.com/en/actions/reference/authentication-in-a-workflow#about-the-github_token-secret) for you, hence you shouldn't need to add it.

**Comment by pierskarsenbarg** [comment]
TIL. I'll close this ticket
