### ISSUE TITLE
Versioning confusion

### ISSUE THREAD

**Issue by wilsonalwaris** [softprops/turnstyle#41]
There seems to be some confusion with the versioning on the marketplace as compared to the usage instructions on readme.

[Turstyle market place url](https://github.com/marketplace/actions/action-turnstyle)

The 'use latest' button recommends using it like shown below 

`- name: action turnstyle
  uses: softprops/turnstyle@v0.1.5
`

But the usage instructions say as shown below. Which is right?

` uses: softprops/turnstyle@v1`

**Comment by ajkerr** [comment]
I seem to get a `Not found` error regardless of which of the two versions I use. 🤔

**Comment by chenrui333** [comment]
Try out v2 or v2.1.0. Thanks!
