### ISSUE TITLE
Deprecated warnings using turnstyle

### ISSUE THREAD

**Issue by thundering-herd** [softprops/turnstyle#51]
Hej,
back in 2022, there was a PR merged which introduced NodeJS 16 but I think it was forgotten to update the `[action.yml](https://github.com/softprops/turnstyle/blob/ca99add00ff0c9cbc697d22631d2992f377e5bd5/action.yml#L8)`

The error show is following:

```
Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: softprops/turnstyle@ca99add00ff0c9cbc697d22631d2992f377e5bd5. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.
```

Thanks

**Comment by jeherve** [comment]
This is also tracked in #43.

**Comment by chenrui333** [comment]
Close as fixed. Thanks!
