### ISSUE TITLE
Required permissions for github token

### ISSUE THREAD

**Issue by paddycarey** [softprops/turnstyle#9]
Hi,

Thanks for the action, it works great! I'm trying to limit the permissions granted to the github token that's used to keep things a little more secure.

Is the minimal set of permissions required for the token used documented anywhere?

Thanks

**Comment by softprops** [comment]
Hi @paddycarey. Thanks for reaching out.

The default `GITHUB_TOKEN` that GitHub provisions for all actions is scoped to the current repository and has [these permissions](https://help.github.com/en/actions/configuring-and-managing-workflows/authenticating-with-the-github_token#permissions-for-the-github_token). Note that the permission given to forks is further restricted to read only. notably actions:read is the permission this action leverages to read the list of running actions. This is documented in [the API](https://developer.github.com/v3/actions/workflow-runs/#list-workflow-runs-for-a-repository)

It is not currently possible to self provision a custom access token that isn't scoped to all of the GitHub repositories the authorized user has access to and dynamically changes scope based so in terms of security blast radius the default token tends to be the most secure by that nature.

**Comment by paddycarey** [comment]
Ah, that makes sense, thanks for the explanation!

I'm new to actions and didn't realise there was an automatically provisioned token, so had created my own 🤦

**Comment by softprops** [comment]
No worries. Enjoy!
